# Generated by Django 3.2.25 on 2024-05-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_alter_prestamo_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lector',
            old_name='appellidos',
            new_name='apellidos',
        ),
        migrations.AlterField(
            model_name='lector',
            name='nacionalidad',
            field=models.CharField(max_length=50),
        ),
    ]
