# Generated by Django 3.2.25 on 2024-05-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_auto_20240512_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='edad',
            field=models.PositiveBigIntegerField(),
        ),
    ]
