# Generated by Django 3.2.25 on 2024-05-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_auto_20240512_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(blank=True, max_length=50, verbose_name='pseudonimo'),
        ),
    ]
